language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
 - nosetests
 - coverage run --source=gang setup.py test
after_success:
  coveralls
